---
abstract: 'Parser for HTML::Template syntax template file & writer.'
author:
  - 'Shigeki Morimoto <Shigeki(at)Morimo.to>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::Template::Parser
name: HTML-Template-Parser
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  Parse::RecDescent: 0
  YAML: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.1009
